// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: communication_message.proto

package sjsu.cmpe.B295.common;

public final class CommunicationMessageProto {
  private CommunicationMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EdgeBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sjsu.cmpe.B295.EdgeBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string msg = 1;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 1;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code sjsu.cmpe.B295.EdgeBeat}
   */
  public static final class EdgeBeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sjsu.cmpe.B295.EdgeBeat)
      EdgeBeatOrBuilder {
    // Use EdgeBeat.newBuilder() to construct.
    private EdgeBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EdgeBeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EdgeBeat defaultInstance;
    public static EdgeBeat getDefaultInstance() {
      return defaultInstance;
    }

    public EdgeBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EdgeBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              msg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.class, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder.class);
    }

    public static com.google.protobuf.Parser<EdgeBeat> PARSER =
        new com.google.protobuf.AbstractParser<EdgeBeat>() {
      public EdgeBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EdgeBeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EdgeBeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSG_FIELD_NUMBER = 1;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 1;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string msg = 1;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sjsu.cmpe.B295.EdgeBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sjsu.cmpe.B295.EdgeBeat)
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.class, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder.class);
      }

      // Construct using sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeat_descriptor;
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat getDefaultInstanceForType() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat build() {
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat buildPartial() {
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat result = new sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) {
          return mergeFrom((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat other) {
        if (other == sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance()) return this;
        if (other.hasMsg()) {
          bitField0_ |= 0x00000001;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 1;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 1;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sjsu.cmpe.B295.EdgeBeat)
    }

    static {
      defaultInstance = new EdgeBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sjsu.cmpe.B295.EdgeBeat)
  }

  public interface EdgeBeatAcknowledgementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sjsu.cmpe.B295.EdgeBeatAcknowledgement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string heartBeatResp = 1;</code>
     */
    boolean hasHeartBeatResp();
    /**
     * <code>optional string heartBeatResp = 1;</code>
     */
    java.lang.String getHeartBeatResp();
    /**
     * <code>optional string heartBeatResp = 1;</code>
     */
    com.google.protobuf.ByteString
        getHeartBeatRespBytes();
  }
  /**
   * Protobuf type {@code sjsu.cmpe.B295.EdgeBeatAcknowledgement}
   */
  public static final class EdgeBeatAcknowledgement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sjsu.cmpe.B295.EdgeBeatAcknowledgement)
      EdgeBeatAcknowledgementOrBuilder {
    // Use EdgeBeatAcknowledgement.newBuilder() to construct.
    private EdgeBeatAcknowledgement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EdgeBeatAcknowledgement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EdgeBeatAcknowledgement defaultInstance;
    public static EdgeBeatAcknowledgement getDefaultInstance() {
      return defaultInstance;
    }

    public EdgeBeatAcknowledgement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EdgeBeatAcknowledgement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              heartBeatResp_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.class, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder.class);
    }

    public static com.google.protobuf.Parser<EdgeBeatAcknowledgement> PARSER =
        new com.google.protobuf.AbstractParser<EdgeBeatAcknowledgement>() {
      public EdgeBeatAcknowledgement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EdgeBeatAcknowledgement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EdgeBeatAcknowledgement> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEARTBEATRESP_FIELD_NUMBER = 1;
    private java.lang.Object heartBeatResp_;
    /**
     * <code>optional string heartBeatResp = 1;</code>
     */
    public boolean hasHeartBeatResp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string heartBeatResp = 1;</code>
     */
    public java.lang.String getHeartBeatResp() {
      java.lang.Object ref = heartBeatResp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          heartBeatResp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string heartBeatResp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHeartBeatRespBytes() {
      java.lang.Object ref = heartBeatResp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heartBeatResp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      heartBeatResp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHeartBeatRespBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHeartBeatRespBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sjsu.cmpe.B295.EdgeBeatAcknowledgement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sjsu.cmpe.B295.EdgeBeatAcknowledgement)
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.class, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder.class);
      }

      // Construct using sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        heartBeatResp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_descriptor;
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement getDefaultInstanceForType() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement build() {
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement buildPartial() {
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement result = new sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.heartBeatResp_ = heartBeatResp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) {
          return mergeFrom((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement other) {
        if (other == sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance()) return this;
        if (other.hasHeartBeatResp()) {
          bitField0_ |= 0x00000001;
          heartBeatResp_ = other.heartBeatResp_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object heartBeatResp_ = "";
      /**
       * <code>optional string heartBeatResp = 1;</code>
       */
      public boolean hasHeartBeatResp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string heartBeatResp = 1;</code>
       */
      public java.lang.String getHeartBeatResp() {
        java.lang.Object ref = heartBeatResp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            heartBeatResp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string heartBeatResp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHeartBeatRespBytes() {
        java.lang.Object ref = heartBeatResp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heartBeatResp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string heartBeatResp = 1;</code>
       */
      public Builder setHeartBeatResp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        heartBeatResp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string heartBeatResp = 1;</code>
       */
      public Builder clearHeartBeatResp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        heartBeatResp_ = getDefaultInstance().getHeartBeatResp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string heartBeatResp = 1;</code>
       */
      public Builder setHeartBeatRespBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        heartBeatResp_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sjsu.cmpe.B295.EdgeBeatAcknowledgement)
    }

    static {
      defaultInstance = new EdgeBeatAcknowledgement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sjsu.cmpe.B295.EdgeBeatAcknowledgement)
  }

  public interface CommunicationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sjsu.cmpe.B295.CommunicationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
     */
    sjsu.cmpe.B295.common.CommonProto.Header getHeader();
    /**
     * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
     */
    sjsu.cmpe.B295.common.CommonProto.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
     *
     * <pre>
     * status updates between adjacent workers
     * </pre>
     */
    boolean hasBeat();
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
     *
     * <pre>
     * status updates between adjacent workers
     * </pre>
     */
    sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat getBeat();
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
     *
     * <pre>
     * status updates between adjacent workers
     * </pre>
     */
    sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder getBeatOrBuilder();

    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
     */
    boolean hasBeatAck();
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
     */
    sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement getBeatAck();
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
     */
    sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder getBeatAckOrBuilder();

    /**
     * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
     */
    boolean hasElectionMessage();
    /**
     * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
     */
    sjsu.cmpe.B295.common.ElectionProto.Election getElectionMessage();
    /**
     * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
     */
    sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder getElectionMessageOrBuilder();
  }
  /**
   * Protobuf type {@code sjsu.cmpe.B295.CommunicationMessage}
   *
   * <pre>
   * These are messages to keep the network running (not to perform work)
   * </pre>
   */
  public static final class CommunicationMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sjsu.cmpe.B295.CommunicationMessage)
      CommunicationMessageOrBuilder {
    // Use CommunicationMessage.newBuilder() to construct.
    private CommunicationMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CommunicationMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CommunicationMessage defaultInstance;
    public static CommunicationMessage getDefaultInstance() {
      return defaultInstance;
    }

    public CommunicationMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CommunicationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              sjsu.cmpe.B295.common.CommonProto.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(sjsu.cmpe.B295.common.CommonProto.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_).toBuilder();
              }
              payload_ = input.readMessage(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_).toBuilder();
              }
              payload_ = input.readMessage(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
            case 34: {
              sjsu.cmpe.B295.common.ElectionProto.Election.Builder subBuilder = null;
              if (payloadCase_ == 4) {
                subBuilder = ((sjsu.cmpe.B295.common.ElectionProto.Election) payload_).toBuilder();
              }
              payload_ = input.readMessage(sjsu.cmpe.B295.common.ElectionProto.Election.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((sjsu.cmpe.B295.common.ElectionProto.Election) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 4;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_CommunicationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_CommunicationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.class, sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<CommunicationMessage> PARSER =
        new com.google.protobuf.AbstractParser<CommunicationMessage>() {
      public CommunicationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommunicationMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CommunicationMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      BEAT(2),
      BEATACK(3),
      ELECTIONMESSAGE(4),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return BEAT;
          case 3: return BEATACK;
          case 4: return ELECTIONMESSAGE;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private sjsu.cmpe.B295.common.CommonProto.Header header_;
    /**
     * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
     */
    public sjsu.cmpe.B295.common.CommonProto.Header getHeader() {
      return header_;
    }
    /**
     * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
     */
    public sjsu.cmpe.B295.common.CommonProto.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    public static final int BEAT_FIELD_NUMBER = 2;
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
     *
     * <pre>
     * status updates between adjacent workers
     * </pre>
     */
    public boolean hasBeat() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
     *
     * <pre>
     * status updates between adjacent workers
     * </pre>
     */
    public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat getBeat() {
      if (payloadCase_ == 2) {
         return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_;
      }
      return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
    }
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
     *
     * <pre>
     * status updates between adjacent workers
     * </pre>
     */
    public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder getBeatOrBuilder() {
      if (payloadCase_ == 2) {
         return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_;
      }
      return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
    }

    public static final int BEATACK_FIELD_NUMBER = 3;
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
     */
    public boolean hasBeatAck() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
     */
    public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement getBeatAck() {
      if (payloadCase_ == 3) {
         return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_;
      }
      return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
    }
    /**
     * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
     */
    public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder getBeatAckOrBuilder() {
      if (payloadCase_ == 3) {
         return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_;
      }
      return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
    }

    public static final int ELECTIONMESSAGE_FIELD_NUMBER = 4;
    /**
     * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
     */
    public boolean hasElectionMessage() {
      return payloadCase_ == 4;
    }
    /**
     * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
     */
    public sjsu.cmpe.B295.common.ElectionProto.Election getElectionMessage() {
      if (payloadCase_ == 4) {
         return (sjsu.cmpe.B295.common.ElectionProto.Election) payload_;
      }
      return sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
    }
    /**
     * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
     */
    public sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder getElectionMessageOrBuilder() {
      if (payloadCase_ == 4) {
         return (sjsu.cmpe.B295.common.ElectionProto.Election) payload_;
      }
      return sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
    }

    private void initFields() {
      header_ = sjsu.cmpe.B295.common.CommonProto.Header.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasElectionMessage()) {
        if (!getElectionMessage().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_);
      }
      if (payloadCase_ == 4) {
        output.writeMessage(4, (sjsu.cmpe.B295.common.ElectionProto.Election) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_);
      }
      if (payloadCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (sjsu.cmpe.B295.common.ElectionProto.Election) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sjsu.cmpe.B295.CommunicationMessage}
     *
     * <pre>
     * These are messages to keep the network running (not to perform work)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sjsu.cmpe.B295.CommunicationMessage)
        sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_CommunicationMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_CommunicationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.class, sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.Builder.class);
      }

      // Construct using sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = sjsu.cmpe.B295.common.CommonProto.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.internal_static_sjsu_cmpe_B295_CommunicationMessage_descriptor;
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage getDefaultInstanceForType() {
        return sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.getDefaultInstance();
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage build() {
        sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage buildPartial() {
        sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage result = new sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (payloadCase_ == 2) {
          if (beatBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = beatBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (beatAckBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = beatAckBuilder_.build();
          }
        }
        if (payloadCase_ == 4) {
          if (electionMessageBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = electionMessageBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage) {
          return mergeFrom((sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage other) {
        if (other == sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        switch (other.getPayloadCase()) {
          case BEAT: {
            mergeBeat(other.getBeat());
            break;
          }
          case BEATACK: {
            mergeBeatAck(other.getBeatAck());
            break;
          }
          case ELECTIONMESSAGE: {
            mergeElectionMessage(other.getElectionMessage());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        if (hasElectionMessage()) {
          if (!getElectionMessage().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjsu.cmpe.B295.common.CommunicationMessageProto.CommunicationMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private sjsu.cmpe.B295.common.CommonProto.Header header_ = sjsu.cmpe.B295.common.CommonProto.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.CommonProto.Header, sjsu.cmpe.B295.common.CommonProto.Header.Builder, sjsu.cmpe.B295.common.CommonProto.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public sjsu.cmpe.B295.common.CommonProto.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public Builder setHeader(sjsu.cmpe.B295.common.CommonProto.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public Builder setHeader(
          sjsu.cmpe.B295.common.CommonProto.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public Builder mergeHeader(sjsu.cmpe.B295.common.CommonProto.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != sjsu.cmpe.B295.common.CommonProto.Header.getDefaultInstance()) {
            header_ =
              sjsu.cmpe.B295.common.CommonProto.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = sjsu.cmpe.B295.common.CommonProto.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public sjsu.cmpe.B295.common.CommonProto.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      public sjsu.cmpe.B295.common.CommonProto.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .sjsu.cmpe.B295.Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.CommonProto.Header, sjsu.cmpe.B295.common.CommonProto.Header.Builder, sjsu.cmpe.B295.common.CommonProto.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sjsu.cmpe.B295.common.CommonProto.Header, sjsu.cmpe.B295.common.CommonProto.Header.Builder, sjsu.cmpe.B295.common.CommonProto.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder> beatBuilder_;
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public boolean hasBeat() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat getBeat() {
        if (beatBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_;
          }
          return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return beatBuilder_.getMessage();
          }
          return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public Builder setBeat(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat value) {
        if (beatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          beatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public Builder setBeat(
          sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder builderForValue) {
        if (beatBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          beatBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public Builder mergeBeat(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat value) {
        if (beatBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance()) {
            payload_ = sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.newBuilder((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            beatBuilder_.mergeFrom(value);
          }
          beatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public Builder clearBeat() {
        if (beatBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          beatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder getBeatBuilder() {
        return getBeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder getBeatOrBuilder() {
        if ((payloadCase_ == 2) && (beatBuilder_ != null)) {
          return beatBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_;
          }
          return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeat beat = 2;</code>
       *
       * <pre>
       * status updates between adjacent workers
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder> 
          getBeatFieldBuilder() {
        if (beatBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.getDefaultInstance();
          }
          beatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat.Builder, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatOrBuilder>(
                  (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeat) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        return beatBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder> beatAckBuilder_;
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public boolean hasBeatAck() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement getBeatAck() {
        if (beatAckBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_;
          }
          return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return beatAckBuilder_.getMessage();
          }
          return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
        }
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public Builder setBeatAck(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement value) {
        if (beatAckBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          beatAckBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public Builder setBeatAck(
          sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder builderForValue) {
        if (beatAckBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          beatAckBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public Builder mergeBeatAck(sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement value) {
        if (beatAckBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance()) {
            payload_ = sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.newBuilder((sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            beatAckBuilder_.mergeFrom(value);
          }
          beatAckBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public Builder clearBeatAck() {
        if (beatAckBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          beatAckBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder getBeatAckBuilder() {
        return getBeatAckFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      public sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder getBeatAckOrBuilder() {
        if ((payloadCase_ == 3) && (beatAckBuilder_ != null)) {
          return beatAckBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_;
          }
          return sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
        }
      }
      /**
       * <code>optional .sjsu.cmpe.B295.EdgeBeatAcknowledgement beatAck = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder> 
          getBeatAckFieldBuilder() {
        if (beatAckBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.getDefaultInstance();
          }
          beatAckBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement.Builder, sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgementOrBuilder>(
                  (sjsu.cmpe.B295.common.CommunicationMessageProto.EdgeBeatAcknowledgement) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        return beatAckBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.ElectionProto.Election, sjsu.cmpe.B295.common.ElectionProto.Election.Builder, sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder> electionMessageBuilder_;
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public boolean hasElectionMessage() {
        return payloadCase_ == 4;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public sjsu.cmpe.B295.common.ElectionProto.Election getElectionMessage() {
        if (electionMessageBuilder_ == null) {
          if (payloadCase_ == 4) {
            return (sjsu.cmpe.B295.common.ElectionProto.Election) payload_;
          }
          return sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
        } else {
          if (payloadCase_ == 4) {
            return electionMessageBuilder_.getMessage();
          }
          return sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
        }
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public Builder setElectionMessage(sjsu.cmpe.B295.common.ElectionProto.Election value) {
        if (electionMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          electionMessageBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public Builder setElectionMessage(
          sjsu.cmpe.B295.common.ElectionProto.Election.Builder builderForValue) {
        if (electionMessageBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          electionMessageBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public Builder mergeElectionMessage(sjsu.cmpe.B295.common.ElectionProto.Election value) {
        if (electionMessageBuilder_ == null) {
          if (payloadCase_ == 4 &&
              payload_ != sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance()) {
            payload_ = sjsu.cmpe.B295.common.ElectionProto.Election.newBuilder((sjsu.cmpe.B295.common.ElectionProto.Election) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 4) {
            electionMessageBuilder_.mergeFrom(value);
          }
          electionMessageBuilder_.setMessage(value);
        }
        payloadCase_ = 4;
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public Builder clearElectionMessage() {
        if (electionMessageBuilder_ == null) {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 4) {
            payloadCase_ = 0;
            payload_ = null;
          }
          electionMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public sjsu.cmpe.B295.common.ElectionProto.Election.Builder getElectionMessageBuilder() {
        return getElectionMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      public sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder getElectionMessageOrBuilder() {
        if ((payloadCase_ == 4) && (electionMessageBuilder_ != null)) {
          return electionMessageBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 4) {
            return (sjsu.cmpe.B295.common.ElectionProto.Election) payload_;
          }
          return sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
        }
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election electionMessage = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          sjsu.cmpe.B295.common.ElectionProto.Election, sjsu.cmpe.B295.common.ElectionProto.Election.Builder, sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder> 
          getElectionMessageFieldBuilder() {
        if (electionMessageBuilder_ == null) {
          if (!(payloadCase_ == 4)) {
            payload_ = sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
          }
          electionMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              sjsu.cmpe.B295.common.ElectionProto.Election, sjsu.cmpe.B295.common.ElectionProto.Election.Builder, sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder>(
                  (sjsu.cmpe.B295.common.ElectionProto.Election) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 4;
        return electionMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:sjsu.cmpe.B295.CommunicationMessage)
    }

    static {
      defaultInstance = new CommunicationMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sjsu.cmpe.B295.CommunicationMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sjsu_cmpe_B295_EdgeBeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sjsu_cmpe_B295_EdgeBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sjsu_cmpe_B295_CommunicationMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sjsu_cmpe_B295_CommunicationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033communication_message.proto\022\016sjsu.cmpe" +
      ".B295\032\014common.proto\032\016election.proto\"\027\n\010E" +
      "dgeBeat\022\013\n\003msg\030\001 \001(\t\"0\n\027EdgeBeatAcknowle" +
      "dgement\022\025\n\rheartBeatResp\030\001 \001(\t\"\344\001\n\024Commu" +
      "nicationMessage\022&\n\006header\030\001 \002(\0132\026.sjsu.c" +
      "mpe.B295.Header\022(\n\004beat\030\002 \001(\0132\030.sjsu.cmp" +
      "e.B295.EdgeBeatH\000\022:\n\007beatAck\030\003 \001(\0132\'.sjs" +
      "u.cmpe.B295.EdgeBeatAcknowledgementH\000\0223\n" +
      "\017electionMessage\030\004 \001(\0132\030.sjsu.cmpe.B295." +
      "ElectionH\000B\t\n\007payloadB4\n\025sjsu.cmpe.B295.",
      "commonB\031CommunicationMessageProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sjsu.cmpe.B295.common.CommonProto.getDescriptor(),
          sjsu.cmpe.B295.common.ElectionProto.getDescriptor(),
        }, assigner);
    internal_static_sjsu_cmpe_B295_EdgeBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sjsu_cmpe_B295_EdgeBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sjsu_cmpe_B295_EdgeBeat_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sjsu_cmpe_B295_EdgeBeatAcknowledgement_descriptor,
        new java.lang.String[] { "HeartBeatResp", });
    internal_static_sjsu_cmpe_B295_CommunicationMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sjsu_cmpe_B295_CommunicationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sjsu_cmpe_B295_CommunicationMessage_descriptor,
        new java.lang.String[] { "Header", "Beat", "BeatAck", "ElectionMessage", "Payload", });
    sjsu.cmpe.B295.common.CommonProto.getDescriptor();
    sjsu.cmpe.B295.common.ElectionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
