// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election.proto

package sjsu.cmpe.B295.common;

public final class ElectionProto {
  private ElectionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ElectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sjsu.cmpe.B295.Election)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
     */
    boolean hasAction();
    /**
     * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
     */
    sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery getAction();

    /**
     * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
     */
    sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState getState();

    /**
     * <code>optional string leader_host = 3;</code>
     */
    boolean hasLeaderHost();
    /**
     * <code>optional string leader_host = 3;</code>
     */
    java.lang.String getLeaderHost();
    /**
     * <code>optional string leader_host = 3;</code>
     */
    com.google.protobuf.ByteString
        getLeaderHostBytes();

    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    int getLeaderId();

    /**
     * <code>optional int32 termId = 5;</code>
     */
    boolean hasTermId();
    /**
     * <code>optional int32 termId = 5;</code>
     */
    int getTermId();

    /**
     * <code>optional int32 votedFor = 6;</code>
     */
    boolean hasVotedFor();
    /**
     * <code>optional int32 votedFor = 6;</code>
     */
    int getVotedFor();

    /**
     * <code>optional bool voteGranted = 7;</code>
     */
    boolean hasVoteGranted();
    /**
     * <code>optional bool voteGranted = 7;</code>
     */
    boolean getVoteGranted();

    /**
     * <code>repeated int32 path = 8;</code>
     *
     * <pre>
     * This will be the list which contains path from current node to leader
     * </pre>
     */
    java.util.List<java.lang.Integer> getPathList();
    /**
     * <code>repeated int32 path = 8;</code>
     *
     * <pre>
     * This will be the list which contains path from current node to leader
     * </pre>
     */
    int getPathCount();
    /**
     * <code>repeated int32 path = 8;</code>
     *
     * <pre>
     * This will be the list which contains path from current node to leader
     * </pre>
     */
    int getPath(int index);
  }
  /**
   * Protobuf type {@code sjsu.cmpe.B295.Election}
   *
   * <pre>
   * enquire about the state of the leader/election
   * </pre>
   */
  public static final class Election extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sjsu.cmpe.B295.Election)
      ElectionOrBuilder {
    // Use Election.newBuilder() to construct.
    private Election(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Election(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Election defaultInstance;
    public static Election getDefaultInstance() {
      return defaultInstance;
    }

    public Election getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Election(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery value = sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                action_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState value = sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              leaderHost_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              leaderId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              termId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              votedFor_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              voteGranted_ = input.readBool();
              break;
            }
            case 64: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                path_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              path_.add(input.readInt32());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
                path_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000080;
              }
              while (input.getBytesUntilLimit() > 0) {
                path_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          path_ = java.util.Collections.unmodifiableList(path_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjsu.cmpe.B295.common.ElectionProto.internal_static_sjsu_cmpe_B295_Election_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjsu.cmpe.B295.common.ElectionProto.internal_static_sjsu_cmpe_B295_Election_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjsu.cmpe.B295.common.ElectionProto.Election.class, sjsu.cmpe.B295.common.ElectionProto.Election.Builder.class);
    }

    public static com.google.protobuf.Parser<Election> PARSER =
        new com.google.protobuf.AbstractParser<Election>() {
      public Election parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Election(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Election> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code sjsu.cmpe.B295.Election.LeaderState}
     */
    public enum LeaderState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEADERUNKNOWN = 1;</code>
       */
      LEADERUNKNOWN(0, 1),
      /**
       * <code>LEADERALIVE = 2;</code>
       */
      LEADERALIVE(1, 2),
      /**
       * <code>LEADERDEAD = 3;</code>
       */
      LEADERDEAD(2, 3),
      ;

      /**
       * <code>LEADERUNKNOWN = 1;</code>
       */
      public static final int LEADERUNKNOWN_VALUE = 1;
      /**
       * <code>LEADERALIVE = 2;</code>
       */
      public static final int LEADERALIVE_VALUE = 2;
      /**
       * <code>LEADERDEAD = 3;</code>
       */
      public static final int LEADERDEAD_VALUE = 3;


      public final int getNumber() { return value; }

      public static LeaderState valueOf(int value) {
        switch (value) {
          case 1: return LEADERUNKNOWN;
          case 2: return LEADERALIVE;
          case 3: return LEADERDEAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<LeaderState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<LeaderState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<LeaderState>() {
              public LeaderState findValueByNumber(int number) {
                return LeaderState.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.ElectionProto.Election.getDescriptor().getEnumTypes().get(0);
      }

      private static final LeaderState[] VALUES = values();

      public static LeaderState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private LeaderState(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sjsu.cmpe.B295.Election.LeaderState)
    }

    /**
     * Protobuf enum {@code sjsu.cmpe.B295.Election.ElectionQuery}
     */
    public enum ElectionQuery
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WHOISTHELEADER = 1;</code>
       */
      WHOISTHELEADER(0, 1),
      /**
       * <code>THELEADERIS = 2;</code>
       */
      THELEADERIS(1, 2),
      /**
       * <code>GETCLUSTERSIZE = 3;</code>
       */
      GETCLUSTERSIZE(2, 3),
      /**
       * <code>SIZEIS = 4;</code>
       */
      SIZEIS(3, 4),
      /**
       * <code>VOTEREQUEST = 5;</code>
       */
      VOTEREQUEST(4, 5),
      /**
       * <code>VOTERESPONSE = 6;</code>
       */
      VOTERESPONSE(5, 6),
      /**
       * <code>BEAT = 7;</code>
       *
       * <pre>
       * Heart Beat between Leader and Followers.
       * </pre>
       */
      BEAT(6, 7),
      ;

      /**
       * <code>WHOISTHELEADER = 1;</code>
       */
      public static final int WHOISTHELEADER_VALUE = 1;
      /**
       * <code>THELEADERIS = 2;</code>
       */
      public static final int THELEADERIS_VALUE = 2;
      /**
       * <code>GETCLUSTERSIZE = 3;</code>
       */
      public static final int GETCLUSTERSIZE_VALUE = 3;
      /**
       * <code>SIZEIS = 4;</code>
       */
      public static final int SIZEIS_VALUE = 4;
      /**
       * <code>VOTEREQUEST = 5;</code>
       */
      public static final int VOTEREQUEST_VALUE = 5;
      /**
       * <code>VOTERESPONSE = 6;</code>
       */
      public static final int VOTERESPONSE_VALUE = 6;
      /**
       * <code>BEAT = 7;</code>
       *
       * <pre>
       * Heart Beat between Leader and Followers.
       * </pre>
       */
      public static final int BEAT_VALUE = 7;


      public final int getNumber() { return value; }

      public static ElectionQuery valueOf(int value) {
        switch (value) {
          case 1: return WHOISTHELEADER;
          case 2: return THELEADERIS;
          case 3: return GETCLUSTERSIZE;
          case 4: return SIZEIS;
          case 5: return VOTEREQUEST;
          case 6: return VOTERESPONSE;
          case 7: return BEAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ElectionQuery>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ElectionQuery>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ElectionQuery>() {
              public ElectionQuery findValueByNumber(int number) {
                return ElectionQuery.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.ElectionProto.Election.getDescriptor().getEnumTypes().get(1);
      }

      private static final ElectionQuery[] VALUES = values();

      public static ElectionQuery valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ElectionQuery(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sjsu.cmpe.B295.Election.ElectionQuery)
    }

    private int bitField0_;
    public static final int ACTION_FIELD_NUMBER = 1;
    private sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery action_;
    /**
     * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
     */
    public sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery getAction() {
      return action_;
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState state_;
    /**
     * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
     */
    public sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState getState() {
      return state_;
    }

    public static final int LEADER_HOST_FIELD_NUMBER = 3;
    private java.lang.Object leaderHost_;
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public boolean hasLeaderHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public java.lang.String getLeaderHost() {
      java.lang.Object ref = leaderHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          leaderHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string leader_host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLeaderHostBytes() {
      java.lang.Object ref = leaderHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADER_ID_FIELD_NUMBER = 4;
    private int leaderId_;
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 leader_id = 4;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int TERMID_FIELD_NUMBER = 5;
    private int termId_;
    /**
     * <code>optional int32 termId = 5;</code>
     */
    public boolean hasTermId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 termId = 5;</code>
     */
    public int getTermId() {
      return termId_;
    }

    public static final int VOTEDFOR_FIELD_NUMBER = 6;
    private int votedFor_;
    /**
     * <code>optional int32 votedFor = 6;</code>
     */
    public boolean hasVotedFor() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 votedFor = 6;</code>
     */
    public int getVotedFor() {
      return votedFor_;
    }

    public static final int VOTEGRANTED_FIELD_NUMBER = 7;
    private boolean voteGranted_;
    /**
     * <code>optional bool voteGranted = 7;</code>
     */
    public boolean hasVoteGranted() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool voteGranted = 7;</code>
     */
    public boolean getVoteGranted() {
      return voteGranted_;
    }

    public static final int PATH_FIELD_NUMBER = 8;
    private java.util.List<java.lang.Integer> path_;
    /**
     * <code>repeated int32 path = 8;</code>
     *
     * <pre>
     * This will be the list which contains path from current node to leader
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getPathList() {
      return path_;
    }
    /**
     * <code>repeated int32 path = 8;</code>
     *
     * <pre>
     * This will be the list which contains path from current node to leader
     * </pre>
     */
    public int getPathCount() {
      return path_.size();
    }
    /**
     * <code>repeated int32 path = 8;</code>
     *
     * <pre>
     * This will be the list which contains path from current node to leader
     * </pre>
     */
    public int getPath(int index) {
      return path_.get(index);
    }

    private void initFields() {
      action_ = sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery.WHOISTHELEADER;
      state_ = sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState.LEADERUNKNOWN;
      leaderHost_ = "";
      leaderId_ = 0;
      termId_ = 0;
      votedFor_ = 0;
      voteGranted_ = false;
      path_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLeaderHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, leaderId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, termId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, votedFor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, voteGranted_);
      }
      for (int i = 0; i < path_.size(); i++) {
        output.writeInt32(8, path_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, action_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLeaderHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, leaderId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, termId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, votedFor_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, voteGranted_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < path_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(path_.get(i));
        }
        size += dataSize;
        size += 1 * getPathList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.ElectionProto.Election parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sjsu.cmpe.B295.common.ElectionProto.Election prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sjsu.cmpe.B295.Election}
     *
     * <pre>
     * enquire about the state of the leader/election
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sjsu.cmpe.B295.Election)
        sjsu.cmpe.B295.common.ElectionProto.ElectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.ElectionProto.internal_static_sjsu_cmpe_B295_Election_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjsu.cmpe.B295.common.ElectionProto.internal_static_sjsu_cmpe_B295_Election_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjsu.cmpe.B295.common.ElectionProto.Election.class, sjsu.cmpe.B295.common.ElectionProto.Election.Builder.class);
      }

      // Construct using sjsu.cmpe.B295.common.ElectionProto.Election.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        action_ = sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery.WHOISTHELEADER;
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState.LEADERUNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        termId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        votedFor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        voteGranted_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        path_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjsu.cmpe.B295.common.ElectionProto.internal_static_sjsu_cmpe_B295_Election_descriptor;
      }

      public sjsu.cmpe.B295.common.ElectionProto.Election getDefaultInstanceForType() {
        return sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance();
      }

      public sjsu.cmpe.B295.common.ElectionProto.Election build() {
        sjsu.cmpe.B295.common.ElectionProto.Election result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sjsu.cmpe.B295.common.ElectionProto.Election buildPartial() {
        sjsu.cmpe.B295.common.ElectionProto.Election result = new sjsu.cmpe.B295.common.ElectionProto.Election(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.leaderHost_ = leaderHost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.termId_ = termId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.votedFor_ = votedFor_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.voteGranted_ = voteGranted_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          path_ = java.util.Collections.unmodifiableList(path_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.path_ = path_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjsu.cmpe.B295.common.ElectionProto.Election) {
          return mergeFrom((sjsu.cmpe.B295.common.ElectionProto.Election)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjsu.cmpe.B295.common.ElectionProto.Election other) {
        if (other == sjsu.cmpe.B295.common.ElectionProto.Election.getDefaultInstance()) return this;
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasLeaderHost()) {
          bitField0_ |= 0x00000004;
          leaderHost_ = other.leaderHost_;
          onChanged();
        }
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (other.hasTermId()) {
          setTermId(other.getTermId());
        }
        if (other.hasVotedFor()) {
          setVotedFor(other.getVotedFor());
        }
        if (other.hasVoteGranted()) {
          setVoteGranted(other.getVoteGranted());
        }
        if (!other.path_.isEmpty()) {
          if (path_.isEmpty()) {
            path_ = other.path_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensurePathIsMutable();
            path_.addAll(other.path_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjsu.cmpe.B295.common.ElectionProto.Election parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjsu.cmpe.B295.common.ElectionProto.Election) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery action_ = sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery.WHOISTHELEADER;
      /**
       * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
       */
      public sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery getAction() {
        return action_;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
       */
      public Builder setAction(sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Election.ElectionQuery action = 1;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = sjsu.cmpe.B295.common.ElectionProto.Election.ElectionQuery.WHOISTHELEADER;
        onChanged();
        return this;
      }

      private sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState state_ = sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState.LEADERUNKNOWN;
      /**
       * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
       */
      public sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState getState() {
        return state_;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
       */
      public Builder setState(sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sjsu.cmpe.B295.Election.LeaderState state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = sjsu.cmpe.B295.common.ElectionProto.Election.LeaderState.LEADERUNKNOWN;
        onChanged();
        return this;
      }

      private java.lang.Object leaderHost_ = "";
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public boolean hasLeaderHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public java.lang.String getLeaderHost() {
        java.lang.Object ref = leaderHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            leaderHost_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLeaderHostBytes() {
        java.lang.Object ref = leaderHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder setLeaderHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        leaderHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder clearLeaderHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        leaderHost_ = getDefaultInstance().getLeaderHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_host = 3;</code>
       */
      public Builder setLeaderHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        leaderHost_ = value;
        onChanged();
        return this;
      }

      private int leaderId_ ;
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000008;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leader_id = 4;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private int termId_ ;
      /**
       * <code>optional int32 termId = 5;</code>
       */
      public boolean hasTermId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 termId = 5;</code>
       */
      public int getTermId() {
        return termId_;
      }
      /**
       * <code>optional int32 termId = 5;</code>
       */
      public Builder setTermId(int value) {
        bitField0_ |= 0x00000010;
        termId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 termId = 5;</code>
       */
      public Builder clearTermId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        termId_ = 0;
        onChanged();
        return this;
      }

      private int votedFor_ ;
      /**
       * <code>optional int32 votedFor = 6;</code>
       */
      public boolean hasVotedFor() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 votedFor = 6;</code>
       */
      public int getVotedFor() {
        return votedFor_;
      }
      /**
       * <code>optional int32 votedFor = 6;</code>
       */
      public Builder setVotedFor(int value) {
        bitField0_ |= 0x00000020;
        votedFor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 votedFor = 6;</code>
       */
      public Builder clearVotedFor() {
        bitField0_ = (bitField0_ & ~0x00000020);
        votedFor_ = 0;
        onChanged();
        return this;
      }

      private boolean voteGranted_ ;
      /**
       * <code>optional bool voteGranted = 7;</code>
       */
      public boolean hasVoteGranted() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool voteGranted = 7;</code>
       */
      public boolean getVoteGranted() {
        return voteGranted_;
      }
      /**
       * <code>optional bool voteGranted = 7;</code>
       */
      public Builder setVoteGranted(boolean value) {
        bitField0_ |= 0x00000040;
        voteGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool voteGranted = 7;</code>
       */
      public Builder clearVoteGranted() {
        bitField0_ = (bitField0_ & ~0x00000040);
        voteGranted_ = false;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> path_ = java.util.Collections.emptyList();
      private void ensurePathIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          path_ = new java.util.ArrayList<java.lang.Integer>(path_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getPathList() {
        return java.util.Collections.unmodifiableList(path_);
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public int getPathCount() {
        return path_.size();
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public int getPath(int index) {
        return path_.get(index);
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public Builder setPath(
          int index, int value) {
        ensurePathIsMutable();
        path_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public Builder addPath(int value) {
        ensurePathIsMutable();
        path_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public Builder addAllPath(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePathIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, path_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 path = 8;</code>
       *
       * <pre>
       * This will be the list which contains path from current node to leader
       * </pre>
       */
      public Builder clearPath() {
        path_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sjsu.cmpe.B295.Election)
    }

    static {
      defaultInstance = new Election(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sjsu.cmpe.B295.Election)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sjsu_cmpe_B295_Election_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sjsu_cmpe_B295_Election_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016election.proto\022\016sjsu.cmpe.B295\"\253\003\n\010Ele" +
      "ction\0226\n\006action\030\001 \002(\0162&.sjsu.cmpe.B295.E" +
      "lection.ElectionQuery\0223\n\005state\030\002 \001(\0162$.s" +
      "jsu.cmpe.B295.Election.LeaderState\022\023\n\013le" +
      "ader_host\030\003 \001(\t\022\021\n\tleader_id\030\004 \001(\005\022\016\n\006te" +
      "rmId\030\005 \001(\005\022\020\n\010votedFor\030\006 \001(\005\022\023\n\013voteGran" +
      "ted\030\007 \001(\010\022\014\n\004path\030\010 \003(\005\"A\n\013LeaderState\022\021" +
      "\n\rLEADERUNKNOWN\020\001\022\017\n\013LEADERALIVE\020\002\022\016\n\nLE" +
      "ADERDEAD\020\003\"\201\001\n\rElectionQuery\022\022\n\016WHOISTHE" +
      "LEADER\020\001\022\017\n\013THELEADERIS\020\002\022\022\n\016GETCLUSTERS",
      "IZE\020\003\022\n\n\006SIZEIS\020\004\022\017\n\013VOTEREQUEST\020\005\022\020\n\014VO" +
      "TERESPONSE\020\006\022\010\n\004BEAT\020\007B&\n\025sjsu.cmpe.B295" +
      ".commonB\rElectionProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sjsu_cmpe_B295_Election_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sjsu_cmpe_B295_Election_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sjsu_cmpe_B295_Election_descriptor,
        new java.lang.String[] { "Action", "State", "LeaderHost", "LeaderId", "TermId", "VotedFor", "VoteGranted", "Path", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
