// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity.proto

package sjsu.cmpe.B295.common;

public final class IdentityProto {
  private IdentityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IdentityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sjsu.cmpe.B295.Identity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
     */
    boolean hasIdentityType();
    /**
     * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
     */
    sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType getIdentityType();

    /**
     * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
     */
    boolean hasNodeState();
    /**
     * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
     */
    sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState getNodeState();

    /**
     * <code>optional string identityStr = 3;</code>
     */
    boolean hasIdentityStr();
    /**
     * <code>optional string identityStr = 3;</code>
     */
    java.lang.String getIdentityStr();
    /**
     * <code>optional string identityStr = 3;</code>
     */
    com.google.protobuf.ByteString
        getIdentityStrBytes();
  }
  /**
   * Protobuf type {@code sjsu.cmpe.B295.Identity}
   */
  public static final class Identity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sjsu.cmpe.B295.Identity)
      IdentityOrBuilder {
    // Use Identity.newBuilder() to construct.
    private Identity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Identity(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Identity defaultInstance;
    public static Identity getDefaultInstance() {
      return defaultInstance;
    }

    public Identity getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Identity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType value = sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                identityType_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState value = sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                nodeState_ = value;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              identityStr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sjsu.cmpe.B295.common.IdentityProto.internal_static_sjsu_cmpe_B295_Identity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sjsu.cmpe.B295.common.IdentityProto.internal_static_sjsu_cmpe_B295_Identity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sjsu.cmpe.B295.common.IdentityProto.Identity.class, sjsu.cmpe.B295.common.IdentityProto.Identity.Builder.class);
    }

    public static com.google.protobuf.Parser<Identity> PARSER =
        new com.google.protobuf.AbstractParser<Identity>() {
      public Identity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Identity(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Identity> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code sjsu.cmpe.B295.Identity.IdentityType}
     */
    public enum IdentityType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CLIENT = 0;</code>
       */
      CLIENT(0, 0),
      /**
       * <code>WORKER = 1;</code>
       */
      WORKER(1, 1),
      ;

      /**
       * <code>CLIENT = 0;</code>
       */
      public static final int CLIENT_VALUE = 0;
      /**
       * <code>WORKER = 1;</code>
       */
      public static final int WORKER_VALUE = 1;


      public final int getNumber() { return value; }

      public static IdentityType valueOf(int value) {
        switch (value) {
          case 0: return CLIENT;
          case 1: return WORKER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IdentityType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<IdentityType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IdentityType>() {
              public IdentityType findValueByNumber(int number) {
                return IdentityType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.IdentityProto.Identity.getDescriptor().getEnumTypes().get(0);
      }

      private static final IdentityType[] VALUES = values();

      public static IdentityType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private IdentityType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sjsu.cmpe.B295.Identity.IdentityType)
    }

    /**
     * Protobuf enum {@code sjsu.cmpe.B295.Identity.NodeState}
     */
    public enum NodeState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LEADER = 0;</code>
       */
      LEADER(0, 0),
      /**
       * <code>CANDIDATE = 1;</code>
       */
      CANDIDATE(1, 1),
      /**
       * <code>FOLLOWER = 2;</code>
       */
      FOLLOWER(2, 2),
      ;

      /**
       * <code>LEADER = 0;</code>
       */
      public static final int LEADER_VALUE = 0;
      /**
       * <code>CANDIDATE = 1;</code>
       */
      public static final int CANDIDATE_VALUE = 1;
      /**
       * <code>FOLLOWER = 2;</code>
       */
      public static final int FOLLOWER_VALUE = 2;


      public final int getNumber() { return value; }

      public static NodeState valueOf(int value) {
        switch (value) {
          case 0: return LEADER;
          case 1: return CANDIDATE;
          case 2: return FOLLOWER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NodeState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<NodeState>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NodeState>() {
              public NodeState findValueByNumber(int number) {
                return NodeState.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.IdentityProto.Identity.getDescriptor().getEnumTypes().get(1);
      }

      private static final NodeState[] VALUES = values();

      public static NodeState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private NodeState(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sjsu.cmpe.B295.Identity.NodeState)
    }

    private int bitField0_;
    public static final int IDENTITYTYPE_FIELD_NUMBER = 1;
    private sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType identityType_;
    /**
     * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
     */
    public boolean hasIdentityType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
     */
    public sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType getIdentityType() {
      return identityType_;
    }

    public static final int NODESTATE_FIELD_NUMBER = 2;
    private sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState nodeState_;
    /**
     * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
     */
    public boolean hasNodeState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
     */
    public sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState getNodeState() {
      return nodeState_;
    }

    public static final int IDENTITYSTR_FIELD_NUMBER = 3;
    private java.lang.Object identityStr_;
    /**
     * <code>optional string identityStr = 3;</code>
     */
    public boolean hasIdentityStr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string identityStr = 3;</code>
     */
    public java.lang.String getIdentityStr() {
      java.lang.Object ref = identityStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          identityStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string identityStr = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIdentityStrBytes() {
      java.lang.Object ref = identityStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      identityType_ = sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType.CLIENT;
      nodeState_ = sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState.LEADER;
      identityStr_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIdentityType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, identityType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, nodeState_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getIdentityStrBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, identityType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, nodeState_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIdentityStrBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static sjsu.cmpe.B295.common.IdentityProto.Identity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sjsu.cmpe.B295.common.IdentityProto.Identity prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sjsu.cmpe.B295.Identity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sjsu.cmpe.B295.Identity)
        sjsu.cmpe.B295.common.IdentityProto.IdentityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sjsu.cmpe.B295.common.IdentityProto.internal_static_sjsu_cmpe_B295_Identity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sjsu.cmpe.B295.common.IdentityProto.internal_static_sjsu_cmpe_B295_Identity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sjsu.cmpe.B295.common.IdentityProto.Identity.class, sjsu.cmpe.B295.common.IdentityProto.Identity.Builder.class);
      }

      // Construct using sjsu.cmpe.B295.common.IdentityProto.Identity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        identityType_ = sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType.CLIENT;
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeState_ = sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState.LEADER;
        bitField0_ = (bitField0_ & ~0x00000002);
        identityStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sjsu.cmpe.B295.common.IdentityProto.internal_static_sjsu_cmpe_B295_Identity_descriptor;
      }

      public sjsu.cmpe.B295.common.IdentityProto.Identity getDefaultInstanceForType() {
        return sjsu.cmpe.B295.common.IdentityProto.Identity.getDefaultInstance();
      }

      public sjsu.cmpe.B295.common.IdentityProto.Identity build() {
        sjsu.cmpe.B295.common.IdentityProto.Identity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sjsu.cmpe.B295.common.IdentityProto.Identity buildPartial() {
        sjsu.cmpe.B295.common.IdentityProto.Identity result = new sjsu.cmpe.B295.common.IdentityProto.Identity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.identityType_ = identityType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeState_ = nodeState_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.identityStr_ = identityStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sjsu.cmpe.B295.common.IdentityProto.Identity) {
          return mergeFrom((sjsu.cmpe.B295.common.IdentityProto.Identity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sjsu.cmpe.B295.common.IdentityProto.Identity other) {
        if (other == sjsu.cmpe.B295.common.IdentityProto.Identity.getDefaultInstance()) return this;
        if (other.hasIdentityType()) {
          setIdentityType(other.getIdentityType());
        }
        if (other.hasNodeState()) {
          setNodeState(other.getNodeState());
        }
        if (other.hasIdentityStr()) {
          bitField0_ |= 0x00000004;
          identityStr_ = other.identityStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdentityType()) {
          
          return false;
        }
        if (!hasNodeState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sjsu.cmpe.B295.common.IdentityProto.Identity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sjsu.cmpe.B295.common.IdentityProto.Identity) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType identityType_ = sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType.CLIENT;
      /**
       * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
       */
      public boolean hasIdentityType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
       */
      public sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType getIdentityType() {
        return identityType_;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
       */
      public Builder setIdentityType(sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        identityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Identity.IdentityType identityType = 1;</code>
       */
      public Builder clearIdentityType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        identityType_ = sjsu.cmpe.B295.common.IdentityProto.Identity.IdentityType.CLIENT;
        onChanged();
        return this;
      }

      private sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState nodeState_ = sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState.LEADER;
      /**
       * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
       */
      public boolean hasNodeState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
       */
      public sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState getNodeState() {
        return nodeState_;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
       */
      public Builder setNodeState(sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        nodeState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sjsu.cmpe.B295.Identity.NodeState nodeState = 2;</code>
       */
      public Builder clearNodeState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeState_ = sjsu.cmpe.B295.common.IdentityProto.Identity.NodeState.LEADER;
        onChanged();
        return this;
      }

      private java.lang.Object identityStr_ = "";
      /**
       * <code>optional string identityStr = 3;</code>
       */
      public boolean hasIdentityStr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string identityStr = 3;</code>
       */
      public java.lang.String getIdentityStr() {
        java.lang.Object ref = identityStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            identityStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string identityStr = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIdentityStrBytes() {
        java.lang.Object ref = identityStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identityStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string identityStr = 3;</code>
       */
      public Builder setIdentityStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        identityStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string identityStr = 3;</code>
       */
      public Builder clearIdentityStr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        identityStr_ = getDefaultInstance().getIdentityStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string identityStr = 3;</code>
       */
      public Builder setIdentityStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        identityStr_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sjsu.cmpe.B295.Identity)
    }

    static {
      defaultInstance = new Identity(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sjsu.cmpe.B295.Identity)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sjsu_cmpe_B295_Identity_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sjsu_cmpe_B295_Identity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016identity.proto\022\016sjsu.cmpe.B295\"\361\001\n\010Ide" +
      "ntity\022;\n\014identityType\030\001 \002(\0162%.sjsu.cmpe." +
      "B295.Identity.IdentityType\0225\n\tnodeState\030" +
      "\002 \002(\0162\".sjsu.cmpe.B295.Identity.NodeStat" +
      "e\022\023\n\013identityStr\030\003 \001(\t\"&\n\014IdentityType\022\n" +
      "\n\006CLIENT\020\000\022\n\n\006WORKER\020\001\"4\n\tNodeState\022\n\n\006L" +
      "EADER\020\000\022\r\n\tCANDIDATE\020\001\022\014\n\010FOLLOWER\020\002B&\n\025" +
      "sjsu.cmpe.B295.commonB\rIdentityProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sjsu_cmpe_B295_Identity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sjsu_cmpe_B295_Identity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sjsu_cmpe_B295_Identity_descriptor,
        new java.lang.String[] { "IdentityType", "NodeState", "IdentityStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
